cloud_provider: "groq" #"ollama"
llm_provider: "groq" #"ollama"
llm_model: "llama-3.1-70b-versatile" #gemma:2b"
embedding_model: "nomic-embed-text:latest"

token_limit: 1000
target_words: 100
chunk_flexbility: 0.25

n_clusters: 13
embed_batch_size: 25
n_closest_representatives: 3

asr_model: "whister tiny"
asr_chunk: 30
